steps:

  # Install node packages
  - name: node:10.16.3
    entrypoint: npm
    args: [ 'install' ]

  # Build productive files
  - name: node:10.16.3
    entrypoint: npm
    args: [ 'run', 'build', '--prod' ]

  # Deploy app
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
